Fix for compilation in DEBUG mode.
The error was:
/home/zampolli/SOFT/alibuild/ali-master/sw/SOURCES/AliPhysics/master/0/PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx:463:27: error: no match for 'operator==' (operand types are 'std::pair<double, double>' and 'const RangeF_t {aka const std::pair<float, float>}')
   assert(params.pion_1_pt == default_pion.pt);

The two pairs are made one of doubles and one of floats. The comparison operator
does not know how to resolve this.